### ISSUE TITLE
GenerateTypes() not working without calling GenerateFile() first

### ISSUE THREAD

**Issue by basilfx** [RicoSuter/NJsonSchema#681]
According to #514, I should be able to use `GenerateTypes()` instead of `GenerateFile()`. I have noticed, using version ~9.10.42~ 9.10.45, that the first doesn't work without calling the latter. In that case, the list of artifacts is empty.

This is the piece of code I am using. It works whenever I uncomment `generator.GenerateFile()`.

```csharp
// Generate class from schema file.
var schema = await JsonSchema4.FromFileAsync(options.Schema);

var settings = new CSharpGeneratorSettings
{
    ArrayType = "System.Collections.Generic.IEnumerable",
    ClassStyle = CSharpClassStyle.Poco,
    Namespace = options.Namespace,
    TypeNameGenerator = new TypeNameGenerator(),
    GenerateJsonMethods = !options.Cleanup
};

var generator = new CSharpGenerator(schema, settings);

// generator.GenerateFile();
var types = generator.GenerateTypes();

// Generate code for each artifact. However, types.Artifacts is empty if GenerateFile isn't invoked first.
foreach (var artifact in types.Artifacts)
{
    // Something with artifact.Code.
}
```

**Comment by RSuter** [comment]
It should be possible... maybe we need to improve the design or document it better.

**Comment by rrmayer** [comment]
So, I discovered this issue while looking into another issue I'm having. It turns out if you write the code using `JsonSchema4`, then you have this issue. If, instead, you use a `SwaggerDocument`, the code generation works properly for `GenerateTypes()`, while `GenerateFile()` fails with a cast exception. There is an issue with the signature of the constructor for CSharpGenerator in that it accepts an `object` type rather than something a little more specific.
