### ISSUE TITLE
Classes with no properties are not generated in C# when base class is INotifyPropertyChanged or BindableBase

### ISSUE THREAD

**Issue by WilfriedRicken** [RicoSuter/NJsonSchema#879]
Classes with no properties are not generated. This is possibly ok in case the class has no base class, but not if the class has a base class like INotifyPropertyChanged or Prism.MVVM.BindableBase.

**Comment by RSuter** [comment]
This is expected behavior - i.e. if a property is of the "any" (i.e. type object with any properties) it is generated as object (C#) or any (TS)… the simplest solution to fix this is to set additionalProperties = false in the schema...

However we could add an execption to this when the property is defined with a schema reference, i.e. the any type is actually defined as a named type in "definitions"...

**Comment by RicoSuter** [comment]
There are now settings like InlineNamedAny which should be set to false and then this should work, please recheck with v10
